### ISSUE TITLE
Traversing each example in the first generated regression tree is wrong

### ISSUE THREAD

**Issue by Hugo101** [starling-lab/rfgb.py#12]
Take Dataset ToyCancer as an example. This is the first built regression tree (MaxDepth = 1):

       - [cancer(C):-  -0.16666666667,  cancer(C):- smokes(C) 0.5]

When building the second tree, we need the leaf node value for each example. As suggested in the ISSUE #11, **3 examples are split into left and right side respectively**. Namely, three should be -1.666666, three should be 0.5.

However, This is the leaf node value for each example in the python version:
![screen shot 2018-07-16 at 9 30 54 pm](https://user-images.githubusercontent.com/18361043/42793492-fb965b0a-893f-11e8-8d89-dcaaf8253b1b.jpg)

I have found where the specific problematic code is.
The problematic function is **learnTree** in _tree.py_
```python
 node.learnedDecisionTree.sort(key = len)
 node.learnedDecisionTree = node.learnedDecisionTree[::-1] #reverse
```
Here sorting would not be correct because of so many decimal numbers which would be counted to the length of **_str_**. Based on the above code, the first tree would be: 

      - [cancer(C):-  -0.16666666667,  cancer(C):- smokes(C) 0.5]
 
Therefore, all leaf node values for each example would be -0.166666666667.

### Solution: keep the value of each clause has the same number of decimals.
Do some modification in function **expandOnBestTest** in _tree.py_.
**the original code:**
``` python
if clause[-1]!='-':
    node.learnedDecisionTree.append(clause[:-1]+" "+str(Utils.getleafValue(self.examples)))
else:
    node.learnedDecisionTree.append(clause+" "+str(Utils.getleafValue(self.examples)))
```
            
**new modified code:**
``` python
from decimal import getcontext, Decimal #added by Changbin
if clause[-1]!='-':
    leafValue = Decimal(Utils.getleafValue(self.examples)).quantize(Decimal('0.000000')) #added by Changbin
    node.learnedDecisionTree.append(clause[:-1]+" "+str(leafValue))          
 else:
    leafValue = Decimal(Utils.getleafValue(self.examples)).quantize(Decimal('0.000000')) #added by Changbin
    node.learnedDecisionTree.append(clause+" "+str(leafValue))          
```

new result is:

      - [cancer(C):- smokes(C) 0.500000,   cancer(C):-  -0.166667]

which could be used to search each example in the tree correctly.

**Comment by batflyer** [comment]
Resolved in fa9a104f64e10e740b70f256ea21e3d2019e7761, closing issue.
