### ISSUE TITLE
Regarding the log prior (phi_0 in the paper)

### ISSUE THREAD

**Issue by Hugo101** [starling-lab/rfgb.py#7]
1.  about the function **performInference** in _boosting.py_ during the inference:
    __logPrior__ = log(0.5/float(1-0.5)) = 0

       However, in the java version, this is -1.8.

2.  about the functions: **setPos** and **setNeg** in _util.py_ during learning:
     
       -  self.pos[example] = 0.5     # Set initial gradient to 0.5 for positives.
       -  self.neg[example] = -0.5   # Set initial gradient to -0.5 for negatives.
 
       However, in the java version: 
       -  For positives, the prob is 1-p=1 - sigmoid(-1.8)
       -  For negatives, the prob is 0-p = 0 - sigmoid(-1.8)

**Comment by batflyer** [comment]
None of the unit tests in this repository check `__logPrior__`, so for the classification case we can simply switch the lines out.

https://github.com/starling-lab/rfgb.py/blob/288fa25613716531c0bf280f2e7fb05a6106d3e6/rfgb/boosting.py#L35

For regression we may want to do something similar to the Java codebase where the prior can be adjusted, maybe as a function in `boosting` or as a parameter in `boosting.updateGradients`.

```diff
- __logPrior__ = log(0.5/float(1-0.5))
+ __logPrior__ = -1.8
+
+ def setLogPrior(prior):
+     __logPrior__ = prior
```

I looked back through [the original RDN-Boost paper](https://starling.utdallas.edu/assets/pdfs/boosting10ilp.pdf) but didn't find this specific value referenced there. @boost-starai  or @gkunapuli may know where this originated from.

**Comment by boost-starai** [comment]
-1.8 is the log prior for 0.5,0.5.

Thanks
Sriraam

P.S. Sent from my phone. Apologies for typos and terseness.

On Jul 17, 2018 16:50, "Alexander L. Hayes" <notifications@github.com> wrote:

None of the unit tests in this repository check __logPrior__, so for the classification case we can simply switch the lines out.

https://github.com/starling-lab/rfgb.py/blob/288fa25613716531c0bf280f2e7fb05a6106d3e6/rfgb/boosting.py#L35

For regression we may want to do something similar to the Java codebase where the prior can be adjusted, maybe as a function in boosting or as a parameter in boosting.updateGradients.

- __logPrior__ = log(0.5/float(1-0.5))
+ __logPrior__ = -1.8
+
+ def setLogPrior(prior):
+     __logPrior__ = prior

I looked back through the original RDN-Boost paper<https://starling.utdallas.edu/assets/pdfs/boosting10ilp.pdf> but didn't find this specific value referenced there. @boost-starai<https://github.com/boost-starai> or @gkunapuli<https://github.com/gkunapuli> may know where this originated from.
