### ISSUE TITLE
computeSumOfGradients after building each new tree

### ISSUE THREAD

**Issue by Hugo101** [starling-lab/rfgb.py#8]
1.  In the function **computeSumOfGradients** in _boosting.py_, it did not consider to add the initialized gradient (namely, phi_0 in the paper) after building each new tree. Therefore, it would not generate the correct answer when the function **updateGradients** in _boosting.py_ calls **computeSumOfGradients**.
However, in the java version, when updating the gradient after building each new tree, the initialized gradient, **-1.8**, would always be added to the new gradient.

2.  When testing, the python version also did not consider this. (function **performInference** in _boosting.py_)

In the Java version, the computation of probability in the testing is like:
          

           -   For pos: p = sigmoid(A+B-1.8)
           -   For neg: p = 1-sigmoid(A+B-1.8)

**Note**: A and B are values of leaf node in each tree (assuming the numOfTrees is 2)
**However**, in the python version, the computation of probability in the testing is like:

           -  For pos: p = sigmoid(A+B)
           -  For neg: p = sigmoid(A+B)

This is still from the function **performInference** in _boosting.py_

**Comment by Hugo101** [comment]
`A` and `B` are the regression values of two trees we built (assuming the model has two trees only, `numOftrees=2`).

**Comment by batflyer** [comment]
Merged into development branch at e85f45d0a026aa8227de183bd12faf3f9073e8de, marking issue as resolved.
